version: '3.1'


services:

  db:
    image: postgres:12
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: P@ssw0rd
    volumes:
      - database_data:/var/lib/postgresql/data


volumes:
  database_data:
    driver: local
